# Generated by Django 3.1.14 on 2024-03-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0026_sensor_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='timezone',
        ),
    ]
