# Generated by Django 3.1.14 on 2024-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0015_syncsensoroverlap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
